"""add_category_is_income

Revision ID: 5a5c9bb61885
Revises: e3f4a5b6c7d8
Create Date: 2026-06-13 12:17:29.790056

"""

from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = "5a5c9bb61885"
down_revision: Union[str, None] = "e3f4a5b6c7d8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "categories",
        sa.Column("is_income", sa.Boolean(), server_default="0", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("categories", "is_income")
    # ### end Alembic commands ###
