"""initial schema

Revision ID: c38e45ddb6bd
Revises: a1b2c3d4e5f6
Create Date: 2026-03-16 22:13:42.784287

"""

from typing import Sequence, Union


revision: str = "c38e45ddb6bd"
down_revision: Union[str, None] = "a1b2c3d4e5f6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
