"""initial schema

Revision ID: ebc343f1c9e6
Revises: 
Create Date: 2026-03-16 20:43:19.267710

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'ebc343f1c9e6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budget_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('allocated_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('category_mappings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('description_pattern', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('match_count', sa.Integer(), nullable=False),
    sa.Column('last_used', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('description_pattern')
    )
    op.create_table('persons',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('raw_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('txn_date', sa.Date(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('processed_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('raw_txn_id', sa.UUID(), nullable=False),
    sa.Column('mapping_id', sa.UUID(), nullable=True),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('txn_date', sa.Date(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('effective_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('split_count', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mapping_id'], ['category_mappings.id'], ),
    sa.ForeignKeyConstraint(['raw_txn_id'], ['raw_transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaction_persons',
    sa.Column('processed_txn_id', sa.UUID(), nullable=False),
    sa.Column('person_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['processed_txn_id'], ['processed_transactions.id'], ),
    sa.PrimaryKeyConstraint('processed_txn_id', 'person_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction_persons')
    op.drop_table('processed_transactions')
    op.drop_table('raw_transactions')
    op.drop_table('persons')
    op.drop_table('category_mappings')
    op.drop_table('budget_plans')
    # ### end Alembic commands ###
